apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "predictionio.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "predictionio.name" . }}
    helm.sh/chart: {{ include "predictionio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.pio.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "predictionio.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "predictionio.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.pio.image.repository }}:{{ .Values.pio.image.tag }}"
          imagePullPolicy: {{ .Values.pio.image.pullPolicy }}
          env:
{{ toYaml .Values.pio.env | indent 12 }}
          ports:
            - name: event
              containerPort: 7070
              protocol: TCP
            - name: predict
              containerPort: 8000
              protocol: TCP
            - name: jupyter
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 7070
          readinessProbe:
            httpGet:
              path: /
              port: 7070
          resources:
{{ toYaml .Values.pio.resources | indent 12 }}
    {{- with .Values.pio.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.pio.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.pio.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
